{"name": "Devilco"}
{"name": "Rurabbi"}
{"name": "Bebe"}
{"name": "Buma"}
{"name": "PoochDev"}
{"name": "Marogni"}
{"name": "Pirosty"}
{"name": "Monggyal"}
{"name": "WildBuma"}
{"name": "MoonRaid"}
{"name": "ArnDev"}
{"name": "Mahollow"}
{"name": "MysticYoyo"}
{"name": "Skullwiser"}
{"name": "Amazonez"}
{"name": "Wiesha"}
{"name": "Pumped"}
{"name": "Tomated"}
{"name": "PumpedCurse"}
{"name": "Kuguto"}
{"name": "Blackened"}
{"name": "PhantomWing-X"}
{"name": "Ordevil"}
{"name": "Devilstone"}
{"name": "Maleki"}
{"name": "NeoOrdevil"}
{"name": "NeoDevilstone"}
{"name": "Saruff"}
{"name": "Banshee"}
{"name": "GateToDeath"}
{"name": "NeoBanshee"}
{"name": "Dalsipper"}
{"name": "NinjaGirl"}
{"name": "Beasco"}
{"name": "Goa"}
{"name": "Nosie"}
{"name": "CryBop"}
{"name": "Turton"}
{"name": "SunEack"}
{"name": "CheezDogg"}
{"name": "Rabie"}
{"name": "MimiEack"}
{"name": "Cowty"}
{"name": "OneStump"}
{"name": "MintRabie"}
{"name": "Liddy"}
{"name": "Torra"}
{"name": "Clawless"}
{"name": "Rrainova"}
{"name": "Dashabell"}
{"name": "MintClaw"}
{"name": "TorraX"}
{"name": "BladeDashabell"}
{"name": "Wagstuff"}
{"name": "GreenTravel"}
{"name": "EvilClaw"}
{"name": "WhiteWags"}
{"name": "MintLion"}
{"name": "Snowfoxy"}
{"name": "Rhine"}
{"name": "BluePigy"}
{"name": "DarkTravel"}
{"name": "MintLionKing"}
{"name": "KingRhine"}
{"name": "NeoKingMintLion"}
{"name": "WindGril"}
{"name": "Metaco"}
{"name": "Metalocks"}
{"name": "BigMaq"}
{"name": "Nippa"}
{"name": "Oilpot"}
{"name": "MechaBall"}
{"name": "Waterball"}
{"name": "Bota"}
{"name": "Monoeye"}
{"name": "TankTortus"}
{"name": "AncientKilla"}
{"name": "Gamerika"}
{"name": "SoulBreaker"}
{"name": "Ayaya"}
{"name": "NeoSoul"}
{"name": "NeoGamerika"}
{"name": "CrimsonMetal"}
{"name": "BomberGun"}
{"name": "NeoAyaya"}
{"name": "TheUnknown"}
{"name": "Gunsmash"}
{"name": "BomberGunMk2"}
{"name": "SilverKun"}
{"name": "Bluemetal"}
{"name": "BomberGunX"}
{"name": "MixDestroyer"}
{"name": "Birdco"}
{"name": "Inseco"}
{"name": "Chicoe"}
{"name": "Caminho"}
{"name": "Pengie"}
{"name": "MelonFlyer"}
{"name": "DooDoo"}
{"name": "Starbird"}
{"name": "ForceFlyer"}
{"name": "HighLife"}
{"name": "Brubli"}
{"name": "NightIme"}
{"name": null}
{"name": "Synicks"}
{"name": "Manta"}
{"name": "Thunderbird"}
{"name": "SwordTail"}
{"name": "Phoenix"}
{"name": "Madtailor"}
{"name": "WingCrusher"}
{"name": "WingStormer"}
{"name": "Rockyrush"}
{"name": "NeoMad"}
{"name": "Harpy"}
{"name": "WingThunder"}
{"name": "Griffin"}
{"name": "Pee"}
{"name": "Bookworm"}
{"name": "SnakeEye"}
{"name": "Mosky"}
{"name": "CabbageFighter"}
{"name": "BellyLady"}
{"name": "NTV"}
{"name": "PayaPaya"}
{"name": "Baccho"}
{"name": "Bolarish"}
{"name": "DayCrawl"}
{"name": "Delcoi"}
{"name": "Asakayza"}
{"name": "HornKing"}
{"name": "BeetlePete"}
{"name": "KingDusty"}
{"name": "BloodStinger"}
{"name": "Kill"}
{"name": "Bamudar"}
{"name": "Siper"}
{"name": "Flowco"}
{"name": "Pioki"}
{"name": "Cupid"}
{"name": "Pioking"}
{"name": "Darkpitt"}
{"name": "KalinAngel\u00a0"}
{"name": "KalinAngel(Fake)"}
{"name": "Mysco"}
{"name": "DevilDusty"}
{"name": "Ziller"}
{"name": "DeadlyBamude"}
{"name": "Siperous"}
{"name": "KillerZill"}
{"name": "QueenSting"}
{"name": "Scorpesis"}
{"name": "Manglock"}
{"name": "Jamoo"}
{"name": "Mameo"}
{"name": "Beanie"}
{"name": "Yeon"}
{"name": "Crutchie"}
{"name": "Nars"}
{"name": "TimTona"}
{"name": "SpineMush"}
{"name": "Lemoni"}
{"name": "Douda"}
{"name": "Pana"}
{"name": "Yassie"}
{"name": "Cactusing"}
{"name": "HornMameo"}
{"name": "Tenkaki"}
{"name": "Chikaki"}
{"name": "Ballza"}
{"name": "Mantyplan"}
{"name": "Shin-Chikaki"}
{"name": "WildBallza"}
{"name": "Flower"}
{"name": "Elder"}
{"name": "Eldering"}
{"name": "NeoSunFlower"}
{"name": "Ukki"}
{"name": "NortsNcross"}
{"name": "RingWorm"}
{"name": "Haneping"}
{"name": "Bangie"}
{"name": "Soo"}
{"name": "Sumping"}
{"name": "Dr.Calvin"}
{"name": "AquaPing"}
{"name": "Chowie"}
{"name": "InsaneDoctor"}
{"name": "Stoner"}
{"name": "Gokuma"}
{"name": "Snogyun"}
{"name": "MacT-Bone"}
{"name": "NeoGokuma"}
{"name": "Binocchio"}
{"name": "Mr.Rupert"}
{"name": "Snowball"}
{"name": "RedLeaf"}
{"name": "Garlingz"}
{"name": "SirPupert"}
{"name": "XT-Bone"}
{"name": "Mintmal"}
{"name": "ShadowMagic"}
{"name": "ArmIris"}
{"name": "Draco"}
{"name": "Pikey"}
{"name": "Imon"}
{"name": "Noa"}
{"name": "Draki"}
{"name": "Gago"}
{"name": "Bigon"}
{"name": "SQ-21"}
{"name": "Kurma"}
{"name": "Deepsuffer"}
{"name": "Mitra"}
{"name": "ArmaBall"}
{"name": "Haedragon"}
{"name": "BattleDragon"}
{"name": "BattleRoyale"}
{"name": "Laustar"}
{"name": "Greentail"}
{"name": "SilverLaustar"}
{"name": "Dragoer"}
{"name": "NeoSilver"}
{"name": "BlazeRhino"}
{"name": "Seki-Shu-Ryu"}
{"name": "Ki-Ryu"}
{"name": "Fairudo"}
{"name": "Fireduke"}
{"name": "NeoSeki-Shu-Ryu"}
{"name": "InfernoDuke"}
{"name": "ProzenRhino"}
{"name": "BlueGarugon"}
{"name": "Garugon"}
